/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The host → shell startup handshake: the host announces that its kkrpc/ws surface is listening and how to authenticate to it. This is the FIRST frame the host sends, so it is versioned like every other cross-boundary DTO — a shell that does not recognise `schemaVersion` must refuse the handshake rather than connect to a surface it cannot speak to.
 */
export interface VRCXKHostReady {
  /**
   * Version of THIS handshake. Bumped only for a breaking shape change; the shell rejects a value it does not implement, which is what turns 'version-skewed sidecar' from a silent half-start into a named failure.
   */
  schemaVersion: 1;
  /**
   * TCP port the host's kkrpc/ws server bound on 127.0.0.1. It binds port 0 and reports the port the OS assigned, so this is always a concrete connectable port — never 0.
   */
  port: number;
  /**
   * Per-launch bearer token (32 random bytes, lowercase hex) that the ws client must present as `?token=`. The pattern is part of the contract, not a stylistic preference: a truncated or uppercased token would be rejected by the host's own comparison, so catching it here names the real fault.
   */
  token: string;
  /**
   * The host build's own version (the same value the ws API `getVersion()` returns, and the one the host already prints in its `ready` log line). Carried here because the shell supervises the host but otherwise has NO way to learn which build it is supervising: `getVersion()` is reachable only over the ws connection the face opens later.
   */
  hostVersion: string;
}
