/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpsUrl = string;
export type Platform = "win32-x64" | "win32-arm64" | "linux-x64" | "linux-arm64" | "darwin-x64" | "darwin-arm64";
/**
 * A semver range, e.g. *, ^1.2, ~2.1.0, >=1.4 <2, =2.1.0. Prereleases are excluded unless the range opts in (^2.0.0-0).
 */
export type VersionRange = string;
/**
 * Service identity: a context key (`notify`) or a provisioned service name (`friendPresence`).
 */
export type ServiceName = string;
/**
 * Used when present; the plugin degrades gracefully when absent.
 *
 * @maxItems 64
 */
export type ServiceList = ServiceName[];
/**
 * Services this plugin PROVIDES. Currently display-only metadata (no dependency resolution consumes it yet); retained because removing it later would be a schema change. Declaring it is what makes a 'library' plugin visible as such.
 *
 * @maxItems 64
 */
export type ServiceList1 = ServiceName[];
/**
 * ctx.shell is the raw escape hatch and can only be granted at SUB-DOMAIN granularity — method-level narrowing is not implementable for it. Keys mirror RAW_SHELL in host/src/capability.ts.
 */
export type ShellSubdomain =
  | "notify"
  | "openUrl"
  | "openPath"
  | "reveal"
  | "dialog"
  | "window"
  | "shortcut"
  | "app"
  | "path"
  | "devWatchEvent"
  | "tray";
export type PermissionGrant = boolean | string[];

/**
 * Author-owned plugin declaration, read from <plugin-root>/.vrcxk/manifest.json. AUTHORITATIVE for version, dependencies, services and permissions. The marketplace index carries only a display cache of name/description; everything else is read from this file. See docs/plugin-source-and-index-design.md.
 */
export interface VRCXKPluginManifest {
  /**
   * Editor-only pointer for autocomplete/validation. IGNORED at load time (Claude Code precedent).
   */
  $schema?: string;
  /**
   * Stable plugin identifier. MUST match the id of the marketplace index entry that references this plugin.
   */
  id: string;
  /**
   * Authoritative semantic version. MUST equal the version segment of the release tag that points at this commit (tag `v1.2.0` or `{id}--v1.2.0`). Checked when installing that ONE version (O(1)), never per-tag.
   */
  version: string;
  /**
   * Required. Part of the identity tuple used to DETECT a change of owner (id + version + author). It is a change detector, not an authenticator: it is self-declared, and differences are reported to the user without blocking (design P2).
   */
  author: string;
  /**
   * Display name. Authoritative; the index copy is only a cache.
   */
  name: string;
  description?: string;
  /**
   * Source repository. Doubles as an identity signal: if it changes for the same id, the user is told.
   */
  repository?: string;
  homepage?: HttpsUrl;
  /**
   * SPDX identifier, e.g. MIT, Apache-2.0.
   */
  license?: string;
  /**
   * Host platforms on which this plugin's NATIVE part can load. Omit for pure JS/TS (the default, and by far the common case). Values are derived from Node semantics `process.platform + '-' + process.arch` — NOT from a Rust target triple and NOT from a bun compile target. This says nothing about clients: the phone runs no host, hence no plugin (docs/mobile-feasibility.md).
   *
   * @minItems 1
   * @maxItems 6
   */
  platforms?:
    | [Platform]
    | [Platform, Platform]
    | [Platform, Platform, Platform]
    | [Platform, Platform, Platform, Platform]
    | [Platform, Platform, Platform, Platform, Platform]
    | [Platform, Platform, Platform, Platform, Platform, Platform];
  /**
   * How a CHANGE to this plugin takes effect. Not a category label: without it the host would restart the whole sidecar even for a UI-only plugin. The two non-default values impose DUTIES on the author (see each description).
   */
  restartClass?: "restartable" | "frontend" | "background";
  /**
   * Plugin dependencies, npm model: a map of plugin id -> version range. NEVER names a source — the author cannot know which sources the user has configured. Sources resolve at install time from the user's current priority list.
   */
  dependencies?: {
    [k: string]: VersionRange;
  };
  services?: Services;
  permissions?: Permissions;
  frontend?: Frontend;
}
/**
 * Service readiness and provision. `required` is a READINESS GATE and is the authority from which the host derives the cordis Entry `inject` (single direction, no drift).
 */
export interface Services {
  /**
   * Readiness gate: the plugin is not started until these are provided. The host derives the cordis Entry `inject` from this list.
   *
   * @maxItems 64
   */
  required?: ServiceName[];
  optional?: ServiceList;
  implements?: ServiceList1;
}
/**
 * Capability declaration for transparency: shown at install time and used for over-privilege WARNINGS. Never enforced (design P2; module-level interception is explicitly not promised).
 */
export interface Permissions {
  /**
   * Raw shell surface. Sub-domain granularity only.
   */
  shell?:
    | boolean
    | []
    | [ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ];
  notify?: PermissionGrant;
  dialog?: PermissionGrant;
  window?: PermissionGrant;
  os?: PermissionGrant;
  tray?: PermissionGrant;
  shortcut?: PermissionGrant;
}
/**
 * Frontend extension point (M3). Omit for headless plugins.
 */
export interface Frontend {
  /**
   * Path to the frontend entry, RELATIVE to the plugin root. Must not escape it: a `..` segment anywhere (including a trailing one, e.g. `ui/..`) is rejected, as is a leading `/`. Note a path regex cannot catch percent-encoding or Windows drive/UNC forms — the loader resolves the path and re-checks containment, which is what actually enforces this.
   */
  entry: string;
  /**
   * Extension points this plugin registers into. The vocabulary lands with the M3 frontend contract.
   *
   * @maxItems 32
   */
  slots?: string[];
}
