/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpsUrl = string;

/**
 * One entry in a plugin SOURCE's index. A source is a table of id -> how to fetch it, plus a DISPLAY CACHE. It is not authoritative about anything that lives in the author's repository: version, permissions, dependencies and checksums are deliberately absent so that publishing a release requires no PR here. See docs/plugin-source-and-index-design.md.
 */
export interface VRCXKPluginIndexEntry {
  /**
   * Stable plugin identifier. Also the key users see as {source}/{id}@{version}.
   */
  id: string;
  /**
   * Official FUNCTION category. Closed enum, and the only machine-reliable filter axis — free tags cannot be (utility/tools/工具 would each be spelled differently). Chosen deliberately narrow so that adding a value later is rare.
   */
  type: "core" | "library" | "feature" | "ui" | "integration" | "tool";
  source: Source;
  /**
   * Display cache. The manifest in the author's repository is authoritative; an out-of-date value here is harmless and self-corrects when the plugin is installed.
   */
  name: string;
  /**
   * Display cache; manifest wins.
   */
  description: string;
  /**
   * Identity signal, mirrored here so a change of owner is visible while browsing. Not an authenticator.
   */
  author: string;
  /**
   * Source repository, used for display and as an identity signal.
   */
  repository: string;
  homepage?: HttpsUrl;
  /**
   * SPDX identifier.
   */
  license?: string;
  /**
   * Free-form, author-chosen labels. Purely presentational: they are NOT a reliable filter axis, which is what `type` is for. Colour is a display-layer concern carried by the source, not the plugin.
   *
   * @maxItems 16
   */
  tags?:
    | []
    | [Tag]
    | [Tag, Tag]
    | [Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag];
}
/**
 * Where to fetch the plugin. This is the index's ONLY authoritative content: without it nothing can be retrieved.
 */
export interface Source {
  /**
   * Git repository URL. MUST end in `.git`: the suffix doubles as the discriminator, which is why there is no `type` field on the source (design P3). NOTE codeload rejects the suffix (404), so any DERIVED url (codeload tarball, raw file) must strip it first — that normalisation belongs in exactly one function.
   */
  url: string;
  /**
   * Plugin directory inside the repository, for monorepos. Omitted = repository root. Must not escape the repository: a `..` segment anywhere (including a trailing one) is rejected, as is a leading `/`. The manifest is read from `<path>/.vrcxk/manifest.json`, so its location is always derivable and needs no field of its own.
   */
  path?: string;
}
export interface Tag {
  label: string;
  /**
   * Optional display colour, taken from the NoneBot store convention [{"label": ..., "color": "#ea5252"}].
   */
  color?: string;
}
