/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpsUrl = string;
/**
 * Operating system only, and deliberately coarse: the ARCHITECTURE is a separate axis (`arch`). A single `windows` value cannot distinguish x64 from arm64, so an x64-only native library would be judged compatible on arm64 — the two fields together express what six combined values would, without a value that mixes the axes.
 */
export type Platform = "windows" | "linux" | "macos";
/**
 * CPU architecture. These are OUR names rather than `process.arch` values, so the schema does not inherit a Node rename; the host maps them when checking.
 */
export type Arch = "x64" | "arm64";
/**
 * A semver range, e.g. *, ^1.2, ~2.1.0, >=1.4 <2, =2.1.0. Prereleases are excluded unless the range opts in (^2.0.0-0).
 */
export type VersionRange = string;
/**
 * Service identity: a context key (`notify`) or a provisioned service name (`friendPresence`). Names that LEAK AN IMPLEMENTATION are rejected: a trailing `Impl`/`Implementation` (e.g. `storageImpl`) or a first-party prefix (`baseStorage`, `officialStorage`). This is the swap-ability guard — a dependency on `storage` can be satisfied by any provider, whereas `baseStorage` bakes one implementation into every dependent's manifest and makes a third-party replacement impossible without editing them all. Must start lowercase so a camelCase service name can never be confused with a kebab-case plugin id.
 */
export type ServiceName = string;
/**
 * Used when present; the plugin degrades gracefully when absent.
 *
 * @maxItems 64
 */
export type ServiceList = ServiceName[];
/**
 * Services this plugin PROVIDES. Currently display-only metadata (no dependency resolution consumes it yet); retained because removing it later would be a schema change. Declaring it is what makes a 'library' plugin visible as such.
 *
 * @maxItems 64
 */
export type ServiceList1 = ServiceName[];
/**
 * ctx.shell is the raw escape hatch and can only be granted at SUB-DOMAIN granularity — method-level narrowing is not implementable for it. Keys mirror RAW_SHELL in host/src/capability.ts.
 */
export type ShellSubdomain =
  | "notify"
  | "openUrl"
  | "openPath"
  | "reveal"
  | "dialog"
  | "window"
  | "shortcut"
  | "app"
  | "path"
  | "devWatchEvent"
  | "tray"
  | "clipboard"
  | "os"
  | "autostart"
  | "deepLink";
export type PermissionGrant = boolean | string[];
/**
 * The file primitives ctx.hands can be granted at, one entry per primitive. PRIMITIVE granularity, not a single boolean and not a path scope: hands is a sharper permission than ctx.shell because it reaches the whole disk, so 'read and stat, never write' must be expressible. Path-scoped grants are deliberately not modelled yet — they need a matcher both sides honour, and the enforcement layer is #13/M4. Keys mirror HANDS_PRIMITIVES in host/src/contracts/capabilityInventory.ts. `list` enumerates ONE directory (non-recursive, unfiltered); matching, sorting and recursion are caller policy, but enumeration ITSELF is a capability only the shell can perform for a remote node.
 */
export type HandsPrimitive = "stat" | "read" | "write" | "watch" | "list";

/**
 * Author-owned plugin declaration, read from <plugin-root>/.vrcxk/manifest.json. AUTHORITATIVE for version, dependencies, services and permissions. The marketplace index carries only a display cache of name/description; everything else is read from this file. See docs/plugin-source-and-index-design.md.
 */
export interface VRCXKPluginManifest {
  /**
   * Editor-only pointer for autocomplete/validation. IGNORED at load time (Claude Code precedent).
   */
  $schema?: string;
  /**
   * Stable plugin identifier. MUST match the id of the marketplace index entry that references this plugin.
   */
  id: string;
  /**
   * Authoritative semantic version. MUST equal the version segment of the release tag that points at this commit (tag `v1.2.0` or `{id}--v1.2.0`). Checked when installing that ONE version (O(1)), never per-tag.
   */
  version: string;
  /**
   * Required. Part of the identity tuple used to DETECT a change of owner (id + version + author). It is a change detector, not an authenticator: it is self-declared, and differences are reported to the user without blocking (design P2).
   */
  author: string;
  /**
   * Display name. Authoritative; the index copy is only a cache.
   */
  name: string;
  description?: string;
  /**
   * Source repository. Doubles as an identity signal: if it changes for the same id, the user is told.
   */
  repository?: string;
  homepage?: HttpsUrl;
  /**
   * SPDX identifier, e.g. MIT, Apache-2.0.
   */
  license?: string;
  /**
   * Operating systems on which this plugin's NATIVE part can load. Omit for pure JS/TS (the default, and the common case) — a pure JS plugin is platform-independent. Pair with `arch` when the plugin bundles native code: the two fields together are what make an x64-only library correctly REJECTED on arm64 rather than installed and then failing at load. This says nothing about clients: the phone runs no host, hence no plugin (docs/mobile-feasibility.md).
   *
   * @minItems 1
   * @maxItems 3
   */
  platforms?: [Platform] | [Platform, Platform] | [Platform, Platform, Platform];
  /**
   * CPU architectures the plugin's native part supports. Only meaningful alongside `platforms`; omitting it means every architecture of those platforms. Required in practice for any plugin shipping a native library, because architecture is exactly the axis a single `platforms` value cannot express.
   *
   * @minItems 1
   * @maxItems 2
   */
  arch?: [Arch] | [Arch, Arch];
  /**
   * How a CHANGE to this plugin takes effect. Not a category label: without it the host would restart the whole sidecar even for a UI-only plugin. The two non-default values impose DUTIES on the author (see each description).
   */
  restartClass?: "restartable" | "frontend" | "background";
  /**
   * Plugin dependencies, npm model: a map of plugin id -> version range. NEVER names a source — the author cannot know which sources the user has configured. Sources resolve at install time from the user's current priority list.
   */
  dependencies?: {
    [k: string]: VersionRange;
  };
  services?: Services;
  permissions?: Permissions;
  frontend?: Frontend;
}
/**
 * Service readiness and provision. `required` is a READINESS GATE and is the authority from which the host derives the cordis Entry `inject` (single direction, no drift).
 */
export interface Services {
  /**
   * Readiness gate: the plugin is not started until these are provided. The host derives the cordis Entry `inject` from this list.
   *
   * @maxItems 64
   */
  required?: ServiceName[];
  optional?: ServiceList;
  implements?: ServiceList1;
}
/**
 * Capability declaration for transparency: shown at install time and used for over-privilege WARNINGS. Never enforced (design P2; module-level interception is explicitly not promised).
 */
export interface Permissions {
  /**
   * Raw shell surface. Sub-domain granularity only. ⚠ `maxItems` MUST equal the `ShellSubdomain` enum length, or a plugin granting every sub-domain has its whole manifest rejected — which silently disables the `#24` warn for exactly the most-privileged plugins. A contract test pins the two together.
   */
  shell?:
    | boolean
    | []
    | [ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain, ShellSubdomain]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ]
    | [
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain,
        ShellSubdomain
      ];
  notify?: PermissionGrant;
  dialog?: PermissionGrant;
  window?: PermissionGrant;
  os?: PermissionGrant;
  tray?: PermissionGrant;
  shortcut?: PermissionGrant;
  /**
   * Text clipboard access (read/write).
   */
  clipboard?: boolean | string[];
  /**
   * Register the app to start with the system. Desktop only; the shell registers no such route on mobile.
   */
  autostart?: boolean | string[];
  /**
   * File primitives (stat/read/write/watch/list). Reaches the whole disk, so prefer a narrow list over `true`. Declaration only at this stage — not enforced (#24 is declare-and-warn, and the real boundary is M4's subprocess isolation). ⚠ `maxItems` MUST equal the `HandsPrimitive` enum length: adding a primitive to the enum without raising this made a 5-primitive grant INVALID, so the manifest was rejected and the `#24` warn silently switched off. A contract test pins the two together.
   */
  hands?:
    | boolean
    | []
    | [HandsPrimitive]
    | [HandsPrimitive, HandsPrimitive]
    | [HandsPrimitive, HandsPrimitive, HandsPrimitive]
    | [HandsPrimitive, HandsPrimitive, HandsPrimitive, HandsPrimitive]
    | [HandsPrimitive, HandsPrimitive, HandsPrimitive, HandsPrimitive, HandsPrimitive];
}
/**
 * Frontend extension point (M3). Omit for headless plugins.
 */
export interface Frontend {
  /**
   * Path to the frontend entry, RELATIVE to the plugin root. Must not escape it: a `..` segment anywhere (including a trailing one, e.g. `ui/..`) is rejected, as is a leading `/`. Note a path regex cannot catch percent-encoding or Windows drive/UNC forms — the loader resolves the path and re-checks containment, which is what actually enforces this.
   */
  entry: string;
  /**
   * Extension points this plugin registers into. The vocabulary lands with the M3 frontend contract.
   *
   * @maxItems 32
   */
  slots?: string[];
}
