/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type TraySource = "core" | "host" | "plugin";
export type TrayItem = TrayActionItem | TrayCheckItem | TrayRadioItem | TraySubmenuItem | TraySeparator;
export type Label = string;
export type TrayActionTarget = "host" | "core";
export type TrayDanger = "safe" | "stateful" | "disruptive" | "destructive";

export interface TrayMenuSnapshot {
  schemaVersion: 1;
  generation: number;
  revision: number;
  /**
   * @maxItems 64
   */
  groups: TrayGroup[];
}
export interface TrayGroup {
  id: Id;
  order: number;
  label: string | null;
  visible: boolean;
  source: TraySource;
  /**
   * @maxItems 512
   */
  items: TrayItem[];
}
export interface TrayActionItem {
  kind: "action";
  id: Id;
  order: number;
  label: Label;
  enabled: boolean;
  visible: boolean;
  action: TrayAction;
}
export interface TrayAction {
  target: TrayActionTarget;
  command: string;
  /**
   * @maxItems 16
   */
  args: unknown[];
  danger: TrayDanger;
  confirm: boolean;
}
export interface TrayCheckItem {
  kind: "check";
  id: Id;
  order: number;
  label: Label;
  enabled: boolean;
  visible: boolean;
  checked: boolean;
  radioGroup: string | null;
  action: TrayAction;
}
export interface TrayRadioItem {
  kind: "radio";
  id: Id;
  order: number;
  label: Label;
  enabled: boolean;
  visible: boolean;
  checked: boolean;
  radioGroup: Id;
  action: TrayAction;
}
export interface TraySubmenuItem {
  kind: "submenu";
  id: Id;
  order: number;
  label: Label;
  enabled: boolean;
  visible: boolean;
  /**
   * @maxItems 512
   */
  items: TrayItem[];
}
export interface TraySeparator {
  kind: "separator";
  id: Id;
  order: number;
  visible: boolean;
}
