import Ajv2020, { type ValidateFunction } from "ajv/dist/2020"
import schema from "../../contracts/tray-menu.schema.json"
import type { TrayMenuSnapshot } from "./tray-contract.generated"

/**
 * Re-exported so consumers import the tray type from the module that owns the
 * contract, not from the generated mirror.
 *
 * ⚠ This was missing, and nothing noticed: the schema, the validator and the
 * `assertTrayMenuSnapshot` guard all lived here, but the TYPE they are all
 * phrased in terms of did not. `tray-contract.test.ts` imported
 * `type TrayMenuSnapshot` from this path and only failed once `host/tests` was
 * added to a tsc program — the generated file is not a stable public path (it is
 * regenerated by `check:contracts`), so reaching past this module for it is a
 * dependency the contract was supposed to hide.
 */
export type { TrayMenuSnapshot }

/** Canonical schema revision for host ↔ Rust tray payloads. */
export const TRAY_SCHEMA_VERSION = 1 as const

const ajv = new Ajv2020({ allErrors: true, strict: true })
export const validateTrayMenuSnapshot: ValidateFunction<TrayMenuSnapshot> = ajv.compile(schema)

export function assertTrayMenuSnapshot(value: unknown): asserts value is TrayMenuSnapshot {
  if (!validateTrayMenuSnapshot(value)) {
    const details = (validateTrayMenuSnapshot.errors ?? [])
      .map((error) => `${error.instancePath} ${error.message}`)
      .join("; ")
    throw new Error(`invalid tray menu snapshot: ${details}`)
  }
}
