/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TrayGroup = HostTrayGroup | CoreTrayGroup;
export type Id = string;
export type Order = number;
export type HostOwnedItem = HostActionItem | HostCheckItem | HostRadioItem | HostSubmenuItem | TraySeparator;
export type Label = string;
export type Command = string;
/**
 * @maxItems 16
 */
export type Args = unknown[];
export type TrayDanger = "safe" | "stateful" | "disruptive" | "destructive";
export type CoreOwnedItem = CoreActionItem | CoreCheckItem | CoreRadioItem | CoreSubmenuItem | TraySeparator;

export interface TrayMenuSnapshot {
  schemaVersion: 1;
  generation: number;
  revision: number;
  /**
   * @maxItems 64
   */
  groups: TrayGroup[];
}
export interface HostTrayGroup {
  id: Id;
  order: Order;
  label: string | null;
  visible: boolean;
  source: "host" | "plugin";
  /**
   * @maxItems 512
   */
  items: HostOwnedItem[];
}
export interface HostActionItem {
  kind: "action";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  action: HostAction;
}
export interface HostAction {
  target: "host";
  command: Command;
  args: Args;
  danger: TrayDanger;
  confirm: boolean;
}
export interface HostCheckItem {
  kind: "check";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  checked: boolean;
  radioGroup: null;
  action: HostAction;
}
export interface HostRadioItem {
  kind: "radio";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  checked: boolean;
  radioGroup: Id;
  action: HostAction;
}
export interface HostSubmenuItem {
  kind: "submenu";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  /**
   * @maxItems 512
   */
  items: HostOwnedItem[];
}
export interface TraySeparator {
  kind: "separator";
  id: Id;
  order: Order;
  visible: boolean;
}
export interface CoreTrayGroup {
  id: Id;
  order: Order;
  label: string | null;
  visible: boolean;
  source: "core";
  /**
   * @maxItems 512
   */
  items: CoreOwnedItem[];
}
export interface CoreActionItem {
  kind: "action";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  action: CoreAction;
}
export interface CoreAction {
  target: "core" | "app";
  command: Command;
  args: Args;
  danger: TrayDanger;
  confirm: boolean;
}
export interface CoreCheckItem {
  kind: "check";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  checked: boolean;
  radioGroup: null;
  action: CoreAction;
}
export interface CoreRadioItem {
  kind: "radio";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  checked: boolean;
  radioGroup: Id;
  action: CoreAction;
}
export interface CoreSubmenuItem {
  kind: "submenu";
  id: Id;
  order: Order;
  label: Label;
  enabled: boolean;
  visible: boolean;
  /**
   * @maxItems 512
   */
  items: CoreOwnedItem[];
}
